# Server port
server.port=8081

# Logging
logging.level.org.springframework.web=INFO

server.servlet.register-default-servlet=true
spring.mvc.view.prefix=/WEB-INF/views/


spring.mvc.view.suffix=.jsp

# File paths for text-based database
data.path=src/main/data/


